#!/bin/env bash

# ensure config
if ! test "$_with_config_" = $$; then
  exec "$(dirname "$(realpath "$0")")/with-config" "$0" "$@"
fi

error() { echo "ERROR $*" >&2; exit 1; }

# get name of part to build
test $# -ge 1 || error "expect at least one argument"
name="$1"
shift

# compute directory locations
srcdir="$ROOTDIR/$name"
blddir="$BUILDDIR/$name"

# check source dir
test -d "$srcdir" || error "no source directory $srcdir"

# create build dir
mkdir -p "$blddir" || error "can't create builddir $blddir"

# prepare build
test "${DEBUG@L}" = yes && mode=DEBUG || mode=RELEASE
cmake -DCMAKE_INSTALL_PREFIX="$PREFIX" -DCMAKE_BUILD_TYPE=$MODE \
   "$@" -B "$blddir"  -S "$srcdir" \
|| error "cmake failed to prepare build"

# build
make -C "$blddir" -j || error "build failed"

# install
make -C "$blddir" install || error "install failed"

