#!/bin/env bash

# ensure config
if ! test "$_with_config_" = $$; then
  exec "$(dirname "$(realpath "$0")")/with-config" "$0" "$@"
fi

error() { echo "ERROR $*" >&2; exit 1; }

# get name of part to build
test $# -ge 1 || error "expect at least one argument"
name="$1"

# compute directory location
blddir="$BUILDDIR/$name"

# remove the build directory
test -d "$blddir" || exit 0
echo "removing $blddir"
rm -r "$blddir"

