#!/bin/env bash
#
# This script check if the configuration file exists
#
# if the configuration file exists extract its values
# in the environment
#
# then if no argument was given, it exits with the status 0
#
# otherwise, is executes the given command in the environment
# that includes the predefined values of the configuration

# definition of ROOTDIR
export ROOTDIR="$(realpath "$(dirname "$0")/..")"

# when a config file exists
config="$ROOTDIR/config"
test -r "$config" && . "$config"

# set default values in case
export BUILDDIR="${BUILDDIR-$ROOTDIR/build}"
export PREFIX="${PREFIX-~/.local}"
export DESTDIR="${DESTDIR-}"
export DEBUG="${DEBUG-no}"

# set common variables with dest
export PKG_CONFIG_PATH="$DESTDIR/$PREFIX/lib64/pkgconfig:$DESTDIR/$PREFIX/lib/pkgconfig:$DESTDIR/$PREFIX/share/pkgconfig:$PKG_CONFIG_PATH"
export MANPATH="$DESTDIR/$PREFIX/share/man:$MANPATH"
export LIBRARY_PATH="$DESTDIR/$PREFIX/lib64:$DESTDIR/$PREFIX/lib:$LIBRARY_PATH"
export LD_LIBRARY_PATH="$DESTDIR/$PREFIX/lib64:$DESTDIR/$PREFIX/lib:$LD_LIBRARY_PATH"
export CPATH="$DESTDIR/$PREFIX/include:$CPATH"
export PATH="$DESTDIR/$PREFIX/bin:$PATH"

# set common variables with prefix
export PKG_CONFIG_PATH="$PREFIX/lib64/pkgconfig:$PREFIX/lib/pkgconfig:$PREFIX/share/pkgconfig:$PKG_CONFIG_PATH"
export MANPATH="$PREFIX/share/man:$MANPATH"
export LIBRARY_PATH="$PREFIX/lib64:$PREFIX/lib:$LIBRARY_PATH"
export LD_LIBRARY_PATH="$PREFIX/lib64:$PREFIX/lib:$LD_LIBRARY_PATH"
export CPATH="$PREFIX/include:$CPATH"
export PATH="$PREFIX/bin:$PATH"

# ok
test 0 -eq $# && exit 0
export _with_config_=$$
exec "$@"

