name: Publish Release

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      
      - name: Run make-archive
        run: scripts/make-archive
      
      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

